persistent_worker:
  container:
    image: alp1n3/local 
    cpu: 24
    memory: 128G
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/persistent-cache:/tmp/cache:ro
  task:
    script: []  # No override of the entry point
