task:
persistent_worker:
  container:
    image: nmlm99/local  # Your custom Docker image
  python_cache:
    folder: /root/.cache/pip  # Cache pip packages
    fingerprint_script: cat requirements.txt  # Use requirements.txt to fingerprint the cache
    populate_script:
      - pip install -r requirements.txt  # Install dependencies (from cache)
  script:
    - python ./os.py  # Run the Python script as the entry point
